package Hibernate;
// Generated Jan 18, 2017 4:22:52 PM by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private String email;
     private String name;
     private int ssn;
     private String password;
     private byte role;

    public Account() {
    }

    public Account(String email, String name, int ssn, String password, byte role) {
       this.email = email;
       this.name = name;
       this.ssn = ssn;
       this.password = password;
       this.role = role;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getSsn() {
        return this.ssn;
    }
    
    public void setSsn(int ssn) {
        this.ssn = ssn;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public byte getRole() {
        return this.role;
    }
    
    public void setRole(byte role) {
        this.role = role;
    }




}


