package Hibernate;
// Generated Jan 18, 2017 4:22:52 PM by Hibernate Tools 4.3.1



/**
 * Snowboard generated by hbm2java
 */
public class Snowboard  implements java.io.Serializable {


     private Integer id;
     private String brandName;
     private String productName;
     private String description;
     private String pictureLink;
     private Integer boardLength;
     private Integer price;

    public Snowboard() {
    }

	
    public Snowboard(String brandName, String productName, String description, String pictureLink) {
        this.brandName = brandName;
        this.productName = productName;
        this.description = description;
        this.pictureLink = pictureLink;
    }
    public Snowboard(String brandName, String productName, String description, String pictureLink, Integer boardLength, Integer price) {
       this.brandName = brandName;
       this.productName = productName;
       this.description = description;
       this.pictureLink = pictureLink;
       this.boardLength = boardLength;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getBrandName() {
        return this.brandName;
    }
    
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPictureLink() {
        return this.pictureLink;
    }
    
    public void setPictureLink(String pictureLink) {
        this.pictureLink = pictureLink;
    }
    public Integer getBoardLength() {
        return this.boardLength;
    }
    
    public void setBoardLength(Integer boardLength) {
        this.boardLength = boardLength;
    }

    /**
     * @return the price
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * @param price the price to set
     */
    public void setPrice(Integer price) {
        this.price = price;
    }




}


